#!/bin/bash

# Скрипт установки и настройки coturn на Ubuntu 22.04
# Автор: WebRTC Messenger Setup
# Версия: 1.0

set -e

echo "🚀 Начинаем установку coturn TURN-сервера..."

# Обновляем систему
echo "📦 Обновляем систему..."
sudo apt update && sudo apt upgrade -y

# Устанавливаем coturn
echo "🔧 Устанавливаем coturn..."
sudo apt install -y coturn

# Получаем внешний IP сервера
EXTERNAL_IP=$(curl -s ifconfig.me)
echo "🌐 Внешний IP сервера: $EXTERNAL_IP"

# Создаем конфигурацию coturn
echo "⚙️ Создаем конфигурацию coturn..."
sudo tee /etc/turnserver.conf > /dev/null <<EOF
# TURN Server Configuration
# Generated by WebRTC Messenger Setup

# Основные настройки
listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0
external-ip=$EXTERNAL_IP

# Аутентификация
user=webrtc:strongpassword
realm=myturn.local

# Безопасность
fingerprint
lt-cred-mech

# Логирование
log-file=/var/log/turn.log
verbose

# Производительность
total-quota=100
bps-capacity=0
stale-nonce=600

# Безопасность
no-multicast-peers
no-cli
no-tlsv1
no-tlsv1_1

# Дополнительные настройки
no-dtls
no-tls
EOF

# Создаем директорию для логов
sudo mkdir -p /var/log
sudo touch /var/log/turn.log
sudo chown turnserver:turnserver /var/log/turn.log

# Включаем автозапуск
echo "🔄 Настраиваем автозапуск..."
sudo systemctl enable coturn
sudo systemctl start coturn

# Проверяем статус
echo "✅ Проверяем статус coturn..."
sudo systemctl status coturn --no-pager

# Открываем порты в UFW
echo "🔥 Настраиваем файрвол..."
sudo ufw allow 3478/udp
sudo ufw allow 5349/tcp
sudo ufw allow 443/tcp
sudo ufw --force enable

# Проверяем, что сервер слушает порты
echo "🔍 Проверяем открытые порты..."
sudo netstat -tulpn | grep -E ":(3478|5349)"

echo ""
echo "🎉 Установка coturn завершена!"
echo ""
echo "📋 Информация о сервере:"
echo "   IP адрес: $EXTERNAL_IP"
echo "   TURN порт: 3478 (UDP)"
echo "   TLS порт: 5349 (TCP)"
echo "   Пользователь: webrtc"
echo "   Пароль: strongpassword"
echo "   Realm: myturn.local"
echo ""
echo "🧪 Тестирование:"
echo "   telnet $EXTERNAL_IP 3478"
echo "   telnet $EXTERNAL_IP 5349"
echo ""
echo "📝 Логи сервера:"
echo "   sudo tail -f /var/log/turn.log"
echo ""
echo "🛠️ Управление сервисом:"
echo "   sudo systemctl status coturn"
echo "   sudo systemctl restart coturn"
echo "   sudo systemctl stop coturn"
echo ""
echo "✅ TURN-сервер готов к использованию!"


